### ISSUE TITLE
Create a GitHub organization (maybe)

### ISSUE THREAD

**Issue by thetredev** [xdeb-org/xdeb-install#11]
Since there are now 4 repositories related to the `xdeb` cosmos we could create a GitHub organization to group all of them. Repos are:
- https://github.com/toluschr/xdeb
- https://github.com/thetredev/xdeb-install/
- https://github.com/thetredev/xdeb-install-repositories/
- https://github.com/thetredev/voidlinux-repository/ (somewhat related, but it could always be converted to be an `xdeb`-only repository)

@toluschr what do you think? I'm not sure about naming things, because there is actually a GitHub user with username xdeb. Maybe `xdeb-voidlinux` or `xdeb-<any TLD>` or something coud fit.

**Comment by toluschr** [comment]
That would be a good idea. I'll look into organizations (and reply to your other issues later), I'm busy dealing with an infection at the moment.

**Comment by thetredev** [comment]
Get well soon!

**Comment by toluschr** [comment]
Do you want to create the organization, or should I? `xdeb` is taken. Perhaps `xdeb-org`?

**Comment by thetredev** [comment]
xdeb-org sounds good. You create it! :)

**Comment by thetredev** [comment]
@toluschr I created a test project with a test release on my account and transferred it to xdeb-org: https://github.com/xdeb-org/test-project-with-releases

So I think this should all go well. I'm gonna transfer my projects this weekend.

**Comment by toluschr** [comment]
> @toluschr I created a test project with a test release on my account and transferred it to xdeb-org: https://github.com/xdeb-org/test-project-with-releases
> 
> So I think this should all go well. I'm gonna transfer my projects this weekend.
> 
> Edit: didn't really have time lol

By default, the organization is setup such that if you upload a repository, I will have read + write access. If I upload a repository, you will only have read access. Transfer your repositories only if you are okay with me being able to commit arbitrarily.

**Comment by thetredev** [comment]
Are we able to change that per repository?

**Comment by toluschr** [comment]
> Are we able to change that per repository?

I don't think so. The organization owner (me) has absolute control. I tried mirroring the repository, but it seems github does not support automatic mirrors.

**Comment by thetredev** [comment]
Oh okay. Pity. Well I think we can we can handle that through other ways.

**Comment by thetredev** [comment]
@toluschr can you give me push access to main branch please? Thanks!
